// Generate Go workspace files for building a custom tsgolint binary.
// With the fork (remorses/tsgolint) exposing pkg/runner.Run(), codegen is
// minimal: a 10-line main.go template + go.work with shim replaces.
// No regex surgery, no file copying, no fragile string manipulation.

import fs from 'node:fs'
import path from 'node:path'
import type { RuleMetadata } from './discover.ts'

// Shim modules that need replace directives in go.work.
// These redirect module paths to local directories inside the tsgolint source.
const SHIM_MODULES = [
  'ast',
  'bundled',
  'checker',
  'compiler',
  'core',
  'lsp/lsproto',
  'parser',
  'project',
  'scanner',
  'tsoptions',
  'tspath',
  'vfs',
  'vfs/cachedvfs',
  'vfs/osvfs',
] as const

function generateReplaceDirectives(tsgolintRelPath: string): string {
  return SHIM_MODULES.map((mod) => {
    return `\tgithub.com/microsoft/typescript-go/shim/${mod} => ${tsgolintRelPath}/shim/${mod}`
  }).join('\n')
}

/** Generate .lintcn/go.work and .lintcn/go.mod for editor/gopls support. */
export function generateEditorGoFiles(lintcnDir: string): void {
  const goWork = `go 1.26

use (
\t.
\t./.tsgolint
\t./.tsgolint/typescript-go
)

replace (
${generateReplaceDirectives('./.tsgolint')}
)
`

  // No child-path hack needed — pkg/ is public, any module name works
  const goMod = `module lintcn-rules

go 1.26
`

  const gitignore = `.tsgolint/
go.work
go.work.sum
go.mod
go.sum
`

  fs.writeFileSync(path.join(lintcnDir, 'go.work'), goWork)
  fs.writeFileSync(path.join(lintcnDir, 'go.mod'), goMod)

  const gitignorePath = path.join(lintcnDir, '.gitignore')
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, gitignore)
  }
}

/** Generate build workspace for compiling the custom binary.
 *  With pkg/runner.Run(), the generated main.go is a static template —
 *  no regex surgery or file copying needed. */
export function generateBuildWorkspace({
  buildDir,
  tsgolintDir,
  lintcnDir,
  rules,
}: {
  buildDir: string
  tsgolintDir: string
  lintcnDir: string
  rules: RuleMetadata[]
}): void {
  fs.mkdirSync(path.join(buildDir, 'wrapper'), { recursive: true })

  // symlink tsgolint source
  const tsgolintLink = path.join(buildDir, 'tsgolint')
  if (fs.existsSync(tsgolintLink)) {
    fs.rmSync(tsgolintLink, { recursive: true })
  }
  fs.symlinkSync(tsgolintDir, tsgolintLink)

  // symlink user rules
  const rulesLink = path.join(buildDir, 'rules')
  if (fs.existsSync(rulesLink)) {
    fs.rmSync(rulesLink, { recursive: true })
  }
  fs.symlinkSync(path.resolve(lintcnDir), rulesLink)

  // go.work
  const goWork = `go 1.26

use (
\t./tsgolint
\t./tsgolint/typescript-go
\t./wrapper
\t./rules
)

replace (
${generateReplaceDirectives('./tsgolint')}
)
`
  fs.writeFileSync(path.join(buildDir, 'go.work'), goWork)

  // wrapper/go.mod — simple module name, no child-path hack needed
  const wrapperGoMod = `module lintcn-wrapper

go 1.26
`
  fs.writeFileSync(path.join(buildDir, 'wrapper', 'go.mod'), wrapperGoMod)

  // wrapper/main.go — simple template, no regex or string surgery
  const mainGo = generateMainGo(rules)
  fs.writeFileSync(path.join(buildDir, 'wrapper', 'main.go'), mainGo)
}

/** Generate a minimal main.go that imports user rules and calls runner.Run().
 *  This is a static template — no copying or patching of tsgolint source. */
function generateMainGo(rules: RuleMetadata[]): string {
  const ruleEntries = rules.map((r) => {
    return `\t\tlintcn.${r.varName},`
  }).join('\n')

  return `// Code generated by lintcn. DO NOT EDIT.
package main

import (
\t"os"

\t"github.com/typescript-eslint/tsgolint/pkg/rule"
\t"github.com/typescript-eslint/tsgolint/pkg/runner"
\tlintcn "lintcn-rules"
)

func main() {
\trules := []rule.Rule{
${ruleEntries}
\t}
\tos.Exit(runner.Run(rules, os.Args[1:]))
}
`
}
